-- Create book table
CREATE TABLE book (
    id BIGSERIAL PRIMARY KEY,
    isbn VARCHAR(13) NOT NULL,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    weight DOUBLE PRECISION NOT NULL,
    height DOUBLE PRECISION NOT NULL,
    width DOUBLE PRECISION NOT NULL,
    enable BOOLEAN NOT NULL DEFAULT FALSE,
    publisher VARCHAR(255),
    description VARCHAR(255),
    created_date TIMESTAMP,
    last_modified_date TIMESTAMP,
    created_by VARCHAR(255),
    last_modified_by VARCHAR(255),
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_book_isbn UNIQUE (isbn)
);

-- Create category table
CREATE TABLE category (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    created_date TIMESTAMP,
    last_modified_date TIMESTAMP,
    created_by VARCHAR(255),
    last_modified_by VARCHAR(255),
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_category_name UNIQUE (name)
);

-- Create book_category join table
CREATE TABLE book_category (
    book_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    PRIMARY KEY (book_id, category_id),
    CONSTRAINT fk_book_category_book FOREIGN KEY (book_id) REFERENCES book(id) ON DELETE CASCADE,
    CONSTRAINT fk_book_category_category FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE CASCADE
);

-- Create type table
CREATE TABLE type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    created_date TIMESTAMP,
    last_modified_date TIMESTAMP,
    created_by VARCHAR(255),
    last_modified_by VARCHAR(255),
    version INTEGER DEFAULT 0
);

CREATE TABLE book_type (
    book_id BIGINT NOT NULL,
    type_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 0,
    created_date TIMESTAMP,
    last_modified_date TIMESTAMP,
    created_by VARCHAR(255),
    last_modified_by VARCHAR(255),
    version INTEGER DEFAULT 0,
    PRIMARY KEY (book_id, type_id),
    CONSTRAINT fk_book_type_book FOREIGN KEY (book_id) REFERENCES book(id) ON DELETE CASCADE,
    CONSTRAINT fk_book_type_type FOREIGN KEY (type_id) REFERENCES type(id) ON DELETE CASCADE,
    CONSTRAINT chk_quantity_non_negative CHECK (quantity >= 0)
);

-- Create review table
CREATE TABLE review (
    id BIGSERIAL PRIMARY KEY,
    content TEXT NOT NULL,
    rating INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    book_id BIGINT NOT NULL,

    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,

    created_date TIMESTAMP,
    last_modified_date TIMESTAMP,
    created_by VARCHAR(255),
    last_modified_by VARCHAR(255),
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT chk_review_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT fk_review_book FOREIGN KEY (book_id) REFERENCES book(id) ON DELETE CASCADE
);

-- Create indexes for better performance
CREATE INDEX idx_book_isbn ON book(isbn);
CREATE INDEX idx_book_title ON book(title);
CREATE INDEX idx_book_author ON book(author);
CREATE INDEX idx_category_name ON category(name);
CREATE INDEX idx_book_type_book_id ON book_type(book_id);
CREATE INDEX idx_book_type_type_id ON book_type(type_id);
CREATE INDEX idx_review_book_id ON review(book_id);
CREATE INDEX idx_review_rating ON review(rating);
CREATE INDEX idx_book_category_book_id ON book_category(book_id);
CREATE INDEX idx_book_category_category_id ON book_category(category_id);